apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.secret.database | quote }}
  MYSQL_USER: {{ .Values.mysql.secret.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.password | quote }}
