apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
    app: wordpress
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      nodePort: {{ .Values.wordpress.service.nodePort }}
